services:
  backend-api:
    build: ./backend-python-api
    container_name: my-python-api-container
    ports:
      - "5698:5698"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend-app:
    build: ./frontend-react
    container_name: my-react-container
    ports:
      - "80:80"  
    restart: always
